### ISSUE TITLE
People In Public in MEVA annotation format

### ISSUE THREAD

**Issue by tea1528** [visym/collector#14]
Hi, thanks for sharing a great dataset and API with the community.

I was wondering if you also provide People In Public annotation in the MEVA style (YAML files with activities, geom, types).

**Comment by jebyrne** [comment]
Hi, there are currently no plans for exporting this dataset in the Kitware style annotation format.  However, there are examples here for going the other way, converting the MEVA YAML files to vipy format:

https://github.com/visym/vipy/blob/master/vipy/dataset/meva.py

It should be a straightforward process to export to MEVA YAML by first exporting each video as JSON using this list comprehension.

```python
video_json = [v.json() for v in vipy.util.load('/path/to/pip_250k.json')]
```
